### PR TITLE
Jacob branch

### PR DESCRIPTION
**Pull request by jsd1710**
I have removed the local.properties file from our repo, moved all image assets from desktop/Bin to Android/assests, and cleaned up unused references. I have tested this to work multiple times and so far have had good luck with eliminating the Pull issue we were facing, where we weren't receiving all image assets. Ensure that your local copy of local.properties is correct, and then this should work with a simple pull.

### CODE REVIEW

**Comment by kole9273** [comment]
We don't want to do full merges, just merge folders core/src, android/assets

**Comment by kole9273** [comment]
But each person's repo is set up for their own machine, including local.properties

**Comment by jsd1710** [comment]
The local.properties file is inappropriate for the repository to watch, where in individual branches or not. It adds an extra step of configuration when checking out to other member's branches. And what do you mean by "full merges"?

**Comment by kole9273** [comment]
If we merged this it adds a ton of .class and .bin files to the master, which we don't want

**Comment by kole9273** [comment]
Also we want to test everything on masterTestBranch, then only merge masterTestBranch into master

**Comment by jsd1710** [comment]
Then I can remove the cached .class and Bin/ files from this branch and attempt to merge into masterTestBranch and then it will be good?

**Comment by kole9273** [comment]
We were mainly adding files into masterTestBranch by being in masterTestBranch locally, then for example using: "Git Checkout drewsBranch core/src"

it manually adds the folders we want, without adding all the extra crap like .class and .bin and local.properties files

**Comment by kole9273** [comment]
And you then don't have to worry about removing cached files either

**Comment by jsd1710** [comment]
While I do agree with the efficiency of checking out a specific directory, we should be able to at any time pull a fresh copy from any branch; create our own local.properties file; import/build from Eclipse; compile the program; and run flawlessly. Anything else is superfluous. Therefore the only files that should be present are .jars, .javas, assests, and other library dependencies needed

**Comment by kole9273** [comment]
Which what we're currently doing allows us to do

**Comment by jsd1710** [comment]
But ignores the fact that our current branches are littered with .class files and bin files regardless to the fact that they are obliterated once Eclipse opens. This is the reason that the assets located in desktop/Bin were not being pulled by us, because the entire Bin folder was being wiped as soon as Eclipse starts

**Comment by kole9273** [comment]
afaik no one is adding their own .class and .bin files anyway. My repo has no cache files, the only difference is the local.properties

**Comment by kole9273** [comment]
If someone is, it's better to not commit those files. always just commit core/src and android/assets

**Comment by kole9273** [comment]
Then others can checkout other's branches when they want. but it's their branch so they can probably do w.e they want with it

**Comment by jsd1710** [comment]
For example, if you browse the masterTestBranch in Github you will see that there is either a Bin or build folder in ios/ desktop/ html/ and android/ or some other directory that contains a .class file. The solution would be for me to purge these from the repository via the "git rm [filename] --cached" command

**Comment by jsd1710** [comment]
And consistency in behavior leads to less purge-work or unnecessary actions.

**Comment by kole9273** [comment]
No, html and ios don't have /bin files, they're the exact same as the master branch atm. Also desktop only has a /bin file because that's where I placed my images initially, there are no cached files there.

**Comment by kole9273** [comment]
I don't know how you got all your bin and class files, I don't think nick has bin/class files either on his repo

**Comment by jsd1710** [comment]
You are misunderstanding the purpose of --cached. It is to logically "unwatch" a file without removing it from your local working directory (so you don't run into runtime issues after performing the action).
As far as html and ios, they have a build folder with a .class:
https://github.com/kole9273/SER316-AsthmaGame/tree/masterTestBranch/html/build/classes/main/com/mygdx/game/client
and
https://github.com/kole9273/SER316-AsthmaGame/tree/masterTestBranch/html/build/classes/main/com/mygdx/game/client

**Comment by kole9273** [comment]
Those must've been initially created from when LibGDX's application created the project as it was added in the initial push of the masterbranch

**Comment by jsd1710** [comment]
Exactly, a purge is necessary, which is what I was proposing.

**Comment by kole9273** [comment]
Not really, we've all pulled from it already and it hasn't caused any problems

**Comment by jsd1710** [comment]
Absence of problems is not an excuse for keeping unnecessary information

**Comment by kole9273** [comment]
Either way, the way we have been doing it doesn't include directories where cache files are

**Comment by jsd1710** [comment]
I agreed with the efficiency of it, but none-the-less we have unnecessary clutter in our repo.

**Comment by kole9273** [comment]
other than those 2 .class files, are there any others?

**Comment by kole9273** [comment]
What we can probably do, is when we're done merging into the masterTestBranch, and everything is working correctly, we can remove the few .class files that got through at the very beginning, before merging into the master branch

**Comment by jsd1710** [comment]
Most recent version of my branch is excluding most .class files that I can see

**Pull request closed without merging**
